# Generated by rebar32nix 0.1.0: rebar32nix . -o outfile.nix
{ stdenv, erlang, fetchHex, fetchgit }:

let
  inherit (builtins) fetchGit;
  rebar32nix_0_1_0 = { rebar3Relx }:
    rebar3Relx {
      name = "rebar32nix";
      version = "0.1.0";
      src = /home/nicolas/dev/work/adgear/rebar32nix/.;
      releaseType = "release";
      beamDeps = [
        erlexec_1_17_5
        getopt_1_0_1
        jsone_1_5_2
      ];
    };
  
  erlexec_1_17_5 = fetchHex {
    pkg = "erlexec";
    version = "1.17.5";
    sha256 = "1zq2h79whjkd9rsrsz2prxs5q544qmjw2b80l7n1kvqlr76dq8ms";
  };
  getopt_1_0_1 = fetchHex {
    pkg = "getopt";
    version = "1.0.1";
    sha256 = "174mb46c2qd1f4a7507fng4vvscjh1ds7rykfab5rdnfp61spqak";
  };
  jsone_1_5_2 = fetchHex {
    pkg = "jsone";
    version = "1.5.2";
    sha256 = "0vwpx8qwlxmn21za3k3d7j1n91av62im8l86b3471pgnwwf1f30p";
  };
in
  erlang.callPackage rebar32nix_0_1_0 { }
